In [2]:
import pandas as pd

In [26]:
road_data = pd.read_csv("F://Road_Accident//Data//train.csv")
road_data_df = road_data.copy()

In [27]:
road_data_df.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56

In [28]:
road_data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       517754 non-null  int64
 1    road_type               517754 non-null  str
 2    num_lanes               517754 non-null  int64
 3    curvature               517754 non-null  float64
 4    speed_limit             517754 non-null  int64
 5    lighting                517754 non-null  str
 6    weather                 517754 non-null  str
 7    road_signs_present      517754 non-null  str
 8    public_road             517754 non-null  str
 9    time_of_day             517754 non-null  str
 10   holiday                 517754 non-null  str
 11   school_season           517754 non-null  str
 12   num_reported_accidents  517754 non-null  int64
 13   accident_risk           517754 non-null  float64
dtypes: float64(2), int64(4), str(8)
memory usage: 100.7 MB

In [29]:
road_data_df.describe()

,id,num_lanes,curvature,speed_limit,num_reported_accidents,accident_risk
count,517754.000000,517754.000000,517754.000000,517754.000000,517754.000000,517754.000000
mean,258876.500000,2.491511,0.488719,46.112575,1.187970,0.352377
std,149462.849975,1.120434,0.272563,15.788521,0.895961,0.166417
min,0.000000,1.000000,0.000000,25.000000,0.000000,0.000000
25%,129438.250000,1.000000,0.260000,35.000000,1.000000,0.230000
50%,258876.500000,2.000000,0.510000,45.000000,1.000000,0.340000
75%,388314.750000,3.000000,0.710000,60.000000,2.000000,0.460000
max,517753.000000,4.000000,1.000000,70.000000,7.000000,1.000000

In [32]:
road_data_df[" road_type"].value_counts()

 road_type
highway      173672
rural        172719
urban        171363
Name: count, dtype: int64

In [33]:
road_data_df[" lighting"].value_counts()

 lighting
dim         183826
daylight    178015
night       155913
Name: count, dtype: int64

In [34]:
road_data_df[" weather"].value_counts()

 weather
foggy      181463
clear      179306
rainy      156985
Name: count, dtype: int64

In [35]:
road_data_df[" time_of_day"].value_counts()

 time_of_day
morning        173410
evening        172837
afternoon      171507
Name: count, dtype: int64

In [ ]:
import sweetviz as sv

report = sv.analyze(road_data_df)
report.show_html("F://Road_Accident//Data_report.html" , open_browser=False)